version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "8383:3000"
    environment:
      - TZ=America/New_York
    volumes:
      - /home/r-server/docker/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - r-server_default

networks:
  r-server_default:
    external: true
