version: "3.8"
services:
  reclaimerr:
    image: ghcr.io/jessielw/reclaimerr:latest
    container_name: reclaimerr
    restart: unless-stopped
    ports:
      - "8977:8977"
    environment:
      - TZ=America/New_York
    volumes:
      - /home/r-server/docker/reclaimerr/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - r-server_default

networks:
  r-server_default:
    external: true
